import React from 'react';
import { Agent, SimulationMessage } from '../types';

interface SimulationViewerProps {
  messages: SimulationMessage[];
  agents: Agent[];
}

const SimulationViewer: React.FC<SimulationViewerProps> = ({ messages, agents }) => {
  
  const getAgentInfo = (name: string) => {
    return agents.find(a => a.name.includes(name) || name.includes(a.name));
  };

  const handleDownload = (format: 'json' | 'md') => {
    let content = '';
    let mimeType = '';
    let extension = '';

    if (format === 'json') {
      content = JSON.stringify(messages, null, 2);
      mimeType = 'application/json';
      extension = 'json';
    } else {
      // Create a nice Markdown format
      content = `# Simulation Log\n\nGenerated by Agentic Workflow Architect\n\n---\n\n`;
      content += messages.map(msg => `**${msg.speaker}**:\n${msg.content}\n`).join('\n---\n\n');
      mimeType = 'text/markdown';
      extension = 'md';
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `simulation-log-${Date.now()}.${extension}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white dark:bg-nb-surface rounded-[32px] border border-gray-200 dark:border-nb-border overflow-hidden mt-8 flex flex-col transition-colors duration-300">
      <div className="px-8 py-6 border-b border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-[#1A1A1A] flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 transition-colors">
        <h2 className="text-gray-900 dark:text-white font-medium text-xl flex items-center gap-3">
          <span className="p-2 bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400 rounded-lg">
             <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z" />
             </svg>
          </span>
          Simulation Log
        </h2>

        {/* Download Options */}
        <div className="flex items-center gap-2">
            <span className="text-xs text-gray-500 uppercase tracking-wider font-semibold mr-1">Download:</span>
            <button 
                onClick={() => handleDownload('json')}
                className="px-3 py-1.5 rounded-lg bg-gray-200 dark:bg-[#2D2D2D] hover:bg-gray-300 dark:hover:bg-[#3D3D3D] text-gray-700 dark:text-gray-300 text-xs font-mono transition-colors border border-gray-300 dark:border-gray-700"
            >
                JSON
            </button>
            <button 
                onClick={() => handleDownload('md')}
                className="px-3 py-1.5 rounded-lg bg-gray-200 dark:bg-[#2D2D2D] hover:bg-gray-300 dark:hover:bg-[#3D3D3D] text-gray-700 dark:text-gray-300 text-xs font-mono transition-colors border border-gray-300 dark:border-gray-700"
            >
                MD
            </button>
        </div>
      </div>
      
      <div className="p-8 bg-white dark:bg-[#131314] space-y-8 max-h-[600px] overflow-y-auto transition-colors">
        {messages.length === 0 ? (
           <p className="text-center text-gray-500 dark:text-gray-600 italic">No dialogue generated yet.</p>
        ) : (
          messages.map((msg, idx) => {
            const agent = getAgentInfo(msg.speaker);
            const avatarUrl = agent?.avatarUrl;
            
            return (
              <div key={idx} className="flex gap-5 animate-fade-in-up group">
                <div className="flex-shrink-0 pt-1">
                  <div className="h-10 w-10 rounded-full overflow-hidden bg-gray-200 dark:bg-gray-700 ring-2 ring-gray-100 dark:ring-[#1E1F20]">
                     {avatarUrl ? (
                       <img src={avatarUrl} alt={msg.speaker} className="h-full w-full object-cover" />
                     ) : (
                       <div className="h-full w-full flex items-center justify-center text-xs font-bold text-gray-500 dark:text-gray-400">
                         {msg.speaker.substring(0,2).toUpperCase()}
                       </div>
                     )}
                  </div>
                </div>
                
                <div className="flex-1 space-y-1">
                   <div className="flex items-baseline gap-2">
                     <span className="text-sm font-bold text-gray-900 dark:text-white">{msg.speaker}</span>
                   </div>
                   <div className="text-gray-700 dark:text-gray-300 text-base leading-relaxed">
                     {msg.content}
                   </div>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};

export default SimulationViewer;