import React, { useState } from 'react';
import { Agent, SimulationMessage, WorkflowData } from '../types';
import AgentDefinitions from './AgentDefinitions';
import ExecutionPrompt from './ExecutionPrompt';
import SimulationViewer from './SimulationViewer';
import WorkflowVisualization from './WorkflowVisualization';
import { generateAgentAvatar, generateSimulationDialogue, generateImplementationGuide, generateWorkflowVisual } from '../services/geminiService';
import { jsPDF } from "jspdf";

interface WorkflowDisplayProps {
  data: WorkflowData;
  onUpdateData: (newData: WorkflowData) => void;
  isDarkMode: boolean;
}

const WorkflowDisplay: React.FC<WorkflowDisplayProps> = ({ data, onUpdateData, isDarkMode }) => {
  const [simStatus, setSimStatus] = useState<'IDLE' | 'GENERATING_AVATARS' | 'GENERATING_DIALOGUE' | 'COMPLETE'>('IDLE');
  const [pdfStatus, setPdfStatus] = useState<'IDLE' | 'GENERATING' | 'COMPLETE'>('IDLE');
  const [visualStatus, setVisualStatus] = useState<'IDLE' | 'GENERATING' | 'COMPLETE'>('IDLE');
  
  const handleExportJson = () => {
    const jsonString = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    
    // Create a filename based on the scenario or timestamp
    const filename = data.scenario 
      ? `workflow-${data.scenario.slice(0, 20).replace(/[^a-z0-9]/gi, '_').toLowerCase()}.json`
      : 'workflow-export.json';
      
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleGeneratePdf = async () => {
    if (!data.scenario) return;
    setPdfStatus('GENERATING');

    try {
        // 1. Fetch Guide content if not present
        let guideText = data.implementationGuide;
        if (!guideText) {
            guideText = await generateImplementationGuide(data.scenario, data.agents);
            // Update state silently to cache it
            onUpdateData({ ...data, implementationGuide: guideText });
        }

        // 2. Initialize PDF
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const margin = 20;
        let yPos = 20;

        // Colors logic for PDF (Always use white background for printability/readability, independent of app theme)
        const COLORS = {
            BG: [255, 255, 255],     
            SURFACE: [245, 247, 250],
            TEXT: [20, 20, 20],   
            ACCENT: [26, 115, 232], // Standard Blue
            DIM: [100, 100, 100]    
        };

        // --- Helper Functions ---
        
        const addBackground = () => {
            doc.setFillColor(COLORS.BG[0], COLORS.BG[1], COLORS.BG[2]);
            doc.rect(0, 0, pageWidth, pageHeight, 'F');
        };

        const addHeader = () => {
             doc.setFont("helvetica", "bold");
             doc.setFontSize(10);
             doc.setTextColor(COLORS.DIM[0], COLORS.DIM[1], COLORS.DIM[2]);
             doc.text("WORKFLOW ARCHITECT REPORT", margin, 15);
             doc.setDrawColor(200, 200, 200);
             doc.line(margin, 18, pageWidth - margin, 18);
        };

        const addFooter = (pageNo: number) => {
            doc.setFontSize(8);
            doc.setTextColor(COLORS.DIM[0], COLORS.DIM[1], COLORS.DIM[2]);
            doc.text(`Page ${pageNo}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
            doc.text(`Generated by Agentic Workflow Architect`, margin, pageHeight - 10);
        };

        const checkPageBreak = (heightNeeded: number) => {
            if (yPos + heightNeeded > pageHeight - margin) {
                const pageCount = doc.internal.getNumberOfPages();
                addFooter(pageCount);
                doc.addPage();
                addBackground();
                addHeader();
                yPos = 30; // Reset Y below header
                return true;
            }
            return false;
        };

        // --- Start Building PDF ---

        // PAGE 1: COVER
        addBackground();
        addHeader();
        yPos = 40;

        // Title
        doc.setFont("helvetica", "bold");
        doc.setFontSize(24);
        doc.setTextColor(COLORS.ACCENT[0], COLORS.ACCENT[1], COLORS.ACCENT[2]);
        const titleLines = doc.splitTextToSize(data.scenario, pageWidth - (margin * 2));
        doc.text(titleLines, margin, yPos);
        yPos += (titleLines.length * 10) + 10;

        // Date & Subtitle
        doc.setFontSize(12);
        doc.setTextColor(COLORS.TEXT[0], COLORS.TEXT[1], COLORS.TEXT[2]);
        doc.text(`Generated on: ${new Date().toLocaleDateString()}`, margin, yPos);
        yPos += 20;

        // Section: Agent Roster
        checkPageBreak(40);
        doc.setFontSize(18);
        doc.setTextColor(COLORS.ACCENT[0], COLORS.ACCENT[1], COLORS.ACCENT[2]);
        doc.text("Agentic Architecture", margin, yPos);
        yPos += 15;

        data.agents.forEach((agent) => {
            // Estimate height for this agent card
            doc.setFontSize(10);
            const roleLines = doc.splitTextToSize(agent.description, pageWidth - margin * 2 - 10);
            const cardHeight = 20 + (roleLines.length * 5);

            checkPageBreak(cardHeight + 10);

            // Draw Card Background
            doc.setFillColor(COLORS.SURFACE[0], COLORS.SURFACE[1], COLORS.SURFACE[2]);
            doc.roundedRect(margin, yPos, pageWidth - (margin * 2), cardHeight, 3, 3, 'F');
            
            // Name
            doc.setFont("helvetica", "bold");
            doc.setFontSize(12);
            doc.setTextColor(COLORS.TEXT[0], COLORS.TEXT[1], COLORS.TEXT[2]);
            doc.text(agent.name, margin + 5, yPos + 10);

            // Role
            doc.setFont("helvetica", "normal");
            doc.setFontSize(10);
            doc.setTextColor(COLORS.DIM[0], COLORS.DIM[1], COLORS.DIM[2]);
            doc.text(roleLines, margin + 5, yPos + 18);

            yPos += cardHeight + 8; // Spacing between cards
        });

        // PAGE BREAK for Visual (If exists)
        if (data.visualUrl) {
            const currentPage = doc.internal.getNumberOfPages();
            addFooter(currentPage);
            doc.addPage();
            addBackground();
            addHeader();
            yPos = 30;

            doc.setFontSize(18);
            doc.setTextColor(COLORS.ACCENT[0], COLORS.ACCENT[1], COLORS.ACCENT[2]);
            doc.setFont("helvetica", "bold");
            doc.text("Workflow Visualization", margin, yPos);
            yPos += 15;

            try {
                // Calculate dimensions to fit within margins
                const imgWidth = pageWidth - (margin * 2);
                const imgHeight = (imgWidth * 9) / 16; // 16:9 aspect ratio

                // Determine format
                const format = data.visualUrl.startsWith('data:image/png') ? 'PNG' : 'JPEG';
                
                doc.addImage(data.visualUrl, format, margin, yPos, imgWidth, imgHeight);
                yPos += imgHeight + 10;
                
                doc.setFontSize(10);
                doc.setTextColor(COLORS.DIM[0], COLORS.DIM[1], COLORS.DIM[2]);
                doc.setFont("helvetica", "italic");
                doc.text("Fig 1. AI-Generated Architecture Diagram", margin, yPos);

            } catch (err) {
                console.error("Failed to add image to PDF", err);
            }
        }

        // PAGE BREAK for Strategy
        const currentPage = doc.internal.getNumberOfPages();
        addFooter(currentPage);
        doc.addPage();
        addBackground();
        addHeader();
        yPos = 30;

        // Section: Strategic Guide
        doc.setFontSize(18);
        doc.setTextColor(COLORS.ACCENT[0], COLORS.ACCENT[1], COLORS.ACCENT[2]);
        doc.setFont("helvetica", "bold");
        doc.text("Strategic Implementation Guide", margin, yPos);
        yPos += 15;

        // Parse and print markdown-ish text
        const lines = guideText.split('\n');
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);

        lines.forEach(line => {
            const cleanLine = line.trim();
            if (!cleanLine) {
                yPos += 5; // Paragraph spacing
                return;
            }

            // Detect Headers (Markdown style # or **Title**)
            const isHeader = cleanLine.startsWith('#') || (cleanLine.startsWith('**') && cleanLine.endsWith('**')) || cleanLine.startsWith('##');
            const isBullet = cleanLine.startsWith('- ') || cleanLine.startsWith('• ');

            // Calculate height needed
            let lineText = cleanLine.replace(/[\*#]/g, ''); // Strip markdown chars
            let textLines = doc.splitTextToSize(lineText, pageWidth - (margin * 2));
            let lineHeight = textLines.length * 6; // line height factor

            checkPageBreak(lineHeight + (isHeader ? 10 : 2));

            if (isHeader) {
                yPos += 5;
                doc.setFont("helvetica", "bold");
                doc.setTextColor(COLORS.ACCENT[0], COLORS.ACCENT[1], COLORS.ACCENT[2]);
                doc.text(lineText, margin, yPos);
                yPos += 8;
                doc.setFont("helvetica", "normal");
            } else {
                doc.setTextColor(COLORS.TEXT[0], COLORS.TEXT[1], COLORS.TEXT[2]);
                if (isBullet) {
                    doc.text(textLines, margin + 5, yPos); // Indent bullets
                } else {
                    doc.text(textLines, margin, yPos);
                }
                yPos += lineHeight;
            }
        });

        // Final Footer for the last page
        const lastPage = doc.internal.getNumberOfPages();
        addFooter(lastPage);

        // Save
        doc.save(`Executive_Report_${data.scenario.slice(0, 15).replace(/[^a-z0-9]/gi, '_')}.pdf`);
        setPdfStatus('COMPLETE');

    } catch (e) {
        console.error("PDF Generation failed", e);
        setPdfStatus('IDLE');
    }
  };

  const handleSimulate = async () => {
    if (!data.scenario) return;
    
    // 1. Generate Avatars if missing
    let updatedAgents = [...data.agents];
    let needsAvatarUpdate = false;

    // Check if any agent is missing an avatar
    if (updatedAgents.some(a => !a.avatarUrl)) {
      setSimStatus('GENERATING_AVATARS');
      
      const avatarPromises = updatedAgents.map(async (agent) => {
        if (agent.avatarUrl) return agent;
        const url = await generateAgentAvatar(agent);
        return { ...agent, avatarUrl: url };
      });

      updatedAgents = await Promise.all(avatarPromises);
      needsAvatarUpdate = true;
    }

    // Save agents immediately if updated, so UI shows avatars while dialogue generates
    if (needsAvatarUpdate) {
       onUpdateData({ ...data, agents: updatedAgents });
    }

    // 2. Generate Dialogue
    setSimStatus('GENERATING_DIALOGUE');
    try {
      const messages = await generateSimulationDialogue(updatedAgents, data.scenario);
      
      onUpdateData({ 
        ...data, 
        agents: updatedAgents, // ensure agents are carried over
        simulationMessages: messages 
      });
      setSimStatus('COMPLETE');
    } catch (e) {
      console.error("Simulation failed", e);
      setSimStatus('IDLE'); // Reset on error
    }
  };

  const handleGenerateVisual = async () => {
    if (!data.scenario) return;
    setVisualStatus('GENERATING');
    try {
      const visualUrl = await generateWorkflowVisual(data.scenario, data.agents);
      onUpdateData({ ...data, visualUrl });
      setVisualStatus('COMPLETE');
    } catch (e) {
      console.error(e);
      setVisualStatus('IDLE');
    }
  };

  return (
    <div className="space-y-10 animate-fade-in-up pb-16">
      
      {/* Top Controls */}
      <div className="flex flex-col md:flex-row justify-end gap-3 flex-wrap">
         <button
          onClick={handleGeneratePdf}
          disabled={pdfStatus === 'GENERATING'}
          className="flex items-center justify-center gap-3 px-6 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl transition-colors shadow-sm text-base font-medium w-full md:w-auto"
        >
          {pdfStatus === 'GENERATING' ? (
             <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
          ) : (
             <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
             </svg>
          )}
          Executive Report (PDF)
        </button>

        <button
          onClick={handleSimulate}
          disabled={simStatus === 'GENERATING_AVATARS' || simStatus === 'GENERATING_DIALOGUE'}
          className={`flex items-center justify-center gap-3 px-6 py-3 rounded-xl text-white text-base font-medium transition-colors shadow-sm w-full md:w-auto
            ${simStatus === 'IDLE' || simStatus === 'COMPLETE' 
              ? 'bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700' 
              : 'bg-gray-400 cursor-not-allowed'}`}
        >
           {simStatus === 'GENERATING_AVATARS' && (
             <>
               <svg className="animate-spin -ml-1 mr-2 h-5 w-5 text-white" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
               Painting Avatars...
             </>
           )}
           {simStatus === 'GENERATING_DIALOGUE' && (
             <>
               <svg className="animate-spin -ml-1 mr-2 h-5 w-5 text-white" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
               Scripting Dialogue...
             </>
           )}
           {(simStatus === 'IDLE' || simStatus === 'COMPLETE') && (
             <>
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              Simulate Workflow
             </>
           )}
        </button>
        
        <button
          onClick={handleExportJson}
          className={`flex items-center justify-center gap-3 px-6 py-3 border rounded-xl transition-colors shadow-sm text-base font-medium w-full md:w-auto ${isDarkMode ? 'bg-gray-800 border-gray-700 text-gray-200 hover:bg-gray-700' : 'bg-white border-gray-200 text-gray-700 hover:bg-gray-50'}`}
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Export JSON
        </button>
      </div>

      {/* Primary Visualization - Dynamic SVG */}
      <WorkflowVisualization agents={data.agents} isDarkMode={isDarkMode} />

      <AgentDefinitions 
        agents={data.agents} 
        onUpdateAgent={(index, updatedAgent) => {
          const newAgents = [...data.agents];
          newAgents[index] = updatedAgent;
          onUpdateData({ ...data, agents: newAgents });
        }}
      />
      
      {data.simulationMessages && data.simulationMessages.length > 0 && (
        <SimulationViewer messages={data.simulationMessages} agents={data.agents} />
      )}

      <ExecutionPrompt 
        prompt={data.executionPrompt}
        onUpdate={(newPrompt) => onUpdateData({ ...data, executionPrompt: newPrompt })}
      />

      {/* AI Visualizer Section - Restored at Bottom */}
      <div className="bg-white dark:bg-nb-surface rounded-[32px] border border-gray-200 dark:border-nb-border overflow-hidden mt-8 transition-colors duration-300 group">
        <div className="px-8 py-6 border-b border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-[#1A1A1A] flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 transition-colors">
            <h2 className="text-gray-900 dark:text-white font-medium text-xl flex items-center gap-3">
                <span className="p-2 bg-pink-100 dark:bg-pink-900/30 text-pink-600 dark:text-pink-400 rounded-lg">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
                </span>
                AI Visual Architect
            </h2>
            {data.visualUrl && (
                <a 
                    href={data.visualUrl} 
                    download={`workflow-infographic-${data.scenario?.slice(0, 10)}.png`}
                    className="flex items-center gap-2 px-4 py-2 rounded-full border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors text-sm"
                >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                    Download High-Res
                </a>
            )}
        </div>

        <div className="p-8 bg-white dark:bg-[#131314] flex flex-col items-center justify-center min-h-[300px] transition-colors relative">
            {/* Background Grid Pattern */}
            <div className="absolute inset-0 opacity-5" style={{ backgroundImage: 'radial-gradient(circle, #888 1px, transparent 1px)', backgroundSize: '20px 20px' }}></div>

            {data.visualUrl ? (
                <div className="relative w-full rounded-2xl overflow-hidden shadow-2xl group-hover:shadow-pink-500/10 transition-shadow">
                    <img 
                        src={data.visualUrl} 
                        alt="AI Generated Workflow Infographic" 
                        className="w-full h-auto object-cover"
                    />
                </div>
            ) : (
                <div className="text-center z-10 max-w-lg">
                    <div className="w-20 h-20 bg-gray-100 dark:bg-gray-800 rounded-full mx-auto mb-6 flex items-center justify-center">
                        <svg className="w-10 h-10 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                        </svg>
                    </div>
                    <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-2">Visualize Your Architecture</h3>
                    <p className="text-gray-500 dark:text-gray-400 mb-8">
                        Generate a stunning 3D isometric infographic of your agent workflow using Google's advanced image generation models. Perfect for pitch decks and technical documentation.
                    </p>
                    <button
                        onClick={handleGenerateVisual}
                        disabled={visualStatus === 'GENERATING'}
                        className={`flex items-center justify-center gap-3 px-8 py-4 rounded-full text-white text-lg font-bold transition-all shadow-lg hover:scale-105 mx-auto
                            ${visualStatus === 'GENERATING' 
                                ? 'bg-gray-600 cursor-not-allowed' 
                                : 'bg-gradient-to-r from-pink-600 to-purple-600 hover:from-pink-500 hover:to-purple-500 shadow-purple-500/25'
                            }`}
                    >
                        {visualStatus === 'GENERATING' ? (
                            <>
                                <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                                Designing Infographic...
                            </>
                        ) : (
                            <>
                                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" /></svg>
                                Generate 3D Infographic
                            </>
                        )}
                    </button>
                </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default WorkflowDisplay;